description = "Hugo port of the Themefisher’s Meghna Template"
features = ['bootstrap', 'responsive']
homepage = "https://gethugothemes.com/products/meghna-hugo-theme/"
license = "MIT"
licenselink = "https://github.com/themefisher/meghna-hugo/blob/master/LICENSE"
min_version = "0.58.0"
name = "Meghna Hugo"
tags = [
  'landing-page',
  'google-analytics',
  'fast',
  'modern',
  'minimal',
  'minimalistic',
  'business',
  'agency-template',
  'themefisher',
  'hugo-theme',
  'hugo-templates',
  'bootstrap',
  'blog',
  'responsive',
  'portfolio',
  'single-page',
  'dark',
  'clean',
  'simple',
  'company',
  'creative',
  'contact-form',
  'custom-themes',
  'mobile',
  'gethugothemes',
]

[author]
homepage = "https://themefisher.com/"
name = "Themefisher"
